name: push-deploy-prod
description: Deploy hello-world to prod

inputs:
  image_tag:
    description: "The tag to be deployed."
    default: latest
    type: string

runs:
  using: "composite"
  steps:

  - uses: actions/checkout@v2
    with:
      repository: mozilla-it/gha-deploy-test

  - id: auth
    uses: google-github-actions/auth@v0
    with:
      workload_identity_provider: projects/312389532942/locations/global/workloadIdentityPools/github-actions/providers/github-actions
      service_account: deploy-prod@opst-82-hello-world.iam.gserviceaccount.com

  - id: get-gke-credentials
    uses: google-github-actions/get-gke-credentials@v0
    with:
      project_id: opst-82-poc
      cluster_name: kubehaus
      location: us-west1

  - uses: hashicorp/setup-terraform@v1
    with:
      terraform_version: 1.1.4

  - name: Deploy the Helm chart with Terraform
    run: |
      terraform init
      terraform apply -auto-approve
    working-directory: projects/hellp-world/tf/prod
    env:
      KUBE_CONFIG_PATH: ${{ env.KUBECONFIG }}
      TF_VAR_image_tag: ${{ inputs.image_tag }}
    shell: sh
