name: push-deploy-prod
description: Deploy hello-world to prod

inputs:
  image_tag:
    description: "The tag to be deployed."
    default: latest
    type: string

runs:
  using: "composite"
  steps:

  - id: auth
    uses: google-github-actions/auth@v0
    with:
      workload_identity_provider: projects/324168772199/locations/global/workloadIdentityPools/github-actions/providers/github-actions
      service_account: deploy-prod@opst-82-poc.iam.gserviceaccount.com
