name: Deploy alpine
on: push
jobs:
  run:
    name: Deploy alpine
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/312389532942/locations/global/workloadIdentityPools/github-actions/providers/github-actions
        service_account: github-actions@opst-82-poc.iam.gserviceaccount.com

    - id: get-gke-credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: kubehaus
        location: us-west1

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.4

    - name: Deploy the Helm chart with Terraform
      run: |
        cd projects/alpine/tf
        export KUBE_CONFIG_PATH="$KUBECONFIG"
        terraform init
        terraform apply -auto-approve
